baseURL = "https://formgate.dev"
languageCode = "en-us"
title = "Formgate"
themesDir = "./themes"
theme = "hugo-whisper-theme"
disableKinds = ["categories", "tags", "taxonomyTerm", "RSS"]

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 100

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 200

[params]
  homepage_button_link = '/docs'
  homeoage_button_text = 'Read The Docs'
  homepage_intro = 'Formgate is a ….'
  homepage_image = '/images/terminal.gif'

  [params.homepage_meta_tags]
    meta_description = "Formgate is a …"
    meta_og_title = "Formgate"
    meta_og_type = "website"
    meta_og_url = "https://formgate.dev"
    meta_og_image = "https://"
    meta_og_description = ""
